---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: whalesay-hello-world-
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/title: '**Whalesay Hello World**'
    workflows.argoproj.io/description: 'This template showcases how to run a simple job with one step'
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: "This workflow was created directly"
  templates:
    - name: whalesay
      inputs:
        parameters:
        - name: message       # parameter declaration
      container:
        # run cowsay with that message input parameter as args
        image: docker.io/docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
