---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capitalator
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: 30-spring-batch-app
    repoURL: https://github.com/alvarolop/spring-batch-capitalator.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
