---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: 31-PostgreSQL/openshift
    repoURL: https://github.com/alvarolop/spring-batch-capitalator.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false



