---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "This project contains Argo Workflows deployment and configuration"
    openshift.io/display-name: "Argo Workflows"
  labels:
    argocd.argoproj.io/managed-by: gitops
  name: argo-workflows