---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
  client-id: "argo-workflows-sso"
  # client-secret: {{ randAlphaNum 300 | quote }}
  client-secret: "MY-SECRET-STRING-CAN-BE-UUID"
