---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cluster-whalesay
  namespace: argo-workflows
spec:
  # run daily at 2am
  schedule: "* * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: whalesay-hello-world-cluster-template
      clusterScope: true
