---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: whalesay
  namespace: argo-workflows
spec:
  # run daily at 2am
  schedule: "* * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: whalesay-hello-world-template
      namespace: argo-workflows