---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: whalesay-cluster
  namespace: argo-workflows
spec:
  event:
    selector: payload.message != "" && discriminator == "cluster-whalesay"
  submit:
    workflowTemplateRef:
      name: whalesay-cluster
      clusterScope: true
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message
