---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: whalesay
  namespace: argo-workflows
spec:
  event:
    selector: payload.message != ""
  submit:
    workflowTemplateRef:
      name: whalesay
      clusterScope: true
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message
