apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: gitops-argocd
  annotations:
    description: Template to deploy a Red Hat Openshift GitOps ArgoCd cluster on OCP.
    tags: argocd,gitops,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:

  - apiVersion: console.openshift.io/v1
    kind: ConsoleLink
    metadata:
      name: ${ARGO_WORKFLOWS_NAMESPACE}-${ARGO_WORKFLOWS_NAME}
    spec:
      href: ${ARGO_WORKFLOWS_ROUTE}
      location: ApplicationMenu
      text: Argo Workflows
      applicationMenu:
        section: GitOps
        imageURL: https://raw.githubusercontent.com/argoproj/argo-workflows/main/docs/assets/logo.png

parameters:
- name: ARGO_WORKFLOWS_ROUTE
  description: "The route to Argo Workflows."
  required: true
- name: ARGO_WORKFLOWS_NAMESPACE
  description: "The project where the cluster will be installed."
  required: false
  value: "argo-workflows"
- name: ARGO_WORKFLOWS_NAME
  description: "The name of the Argo Workflows cluster."
  required: false
  value: "cluster"