kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.dex.name }}-sa-token
  namespace: {{ $.Values.dex.namespace | default $.Values.global.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $.Values.dex.name }}
type: kubernetes.io/service-account-token
