---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cluster-workflow-template-whalesay-hello-world-
  namespace: argo-workflows
spec:
  arguments:
    parameters:
      - name: message
        value: "This Workflow is launched from a Cluster Workflow Template!!"
  workflowTemplateRef:
    name: whalesay-hello-world-template
    clusterScope: true
