{{- if $.Values.global.createGroups }}
{{- range $group := $.Values.global.createGroups }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ $group.name }}
users:
  - {{ $group.user }}
{{- end }}
{{- end }}