{{- range $sa := $.Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $sa.namespace | default $.Values.default.saNamespace }}
  {{- if $sa.labels -}}
  labels:
    {{- toYaml $sa.labels | nindent 4 }}
  {{- end }}
  annotations:
    workflows.argoproj.io/rbac-rule: {{ $sa.rbacRule | quote }}
    workflows.argoproj.io/rbac-rule-precedence: {{ $sa.rbacPrecedence | quote }}
automountServiceAccountToken: true
secrets:
  - name: {{ $sa.tokenName }}
{{- end }}
