---
# https://github.com/argoproj/argo-workflows/discussions/9496
# https://github.com/argoproj/argo-workflows/issues/8320
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.name }}-default-token
  namespace: {{ $.Values.global.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $.Values.global.name }}-default
type: kubernetes.io/service-account-token
