---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.name }}-default
  namespace: {{ $.Values.global.namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: "'system:authenticated' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "0"
automountServiceAccountToken: true
secrets:
  - name: {{ $.Values.global.name }}-default-token
