{{- range $rbac := $.Values.rbac }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.name }}-{{ $rbac.group }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    workflows.argoproj.io/rbac-rule: "'{{ $rbac.group }}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: {{ $rbac.precedence | quote }}
automountServiceAccountToken: true
secrets:
  - name: {{ $.Values.global.name }}-{{ $rbac.group }}-token
{{- end }}