---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgresql-credentials
  namespace: postgresql
stringData:
  database-name: capitalator
  database-password: password
  database-user: capitalator-user
