---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgresql-credentials
  namespace: postgresql
stringData:
  database-name: datagrid
  database-password: password
  database-user: rhdguser
