---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: db
  namespace: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP
